version: '3.9'
services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always

  mysql:
    image: mysql
    container_name: message-data
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: message
    ports:
      - 3307:3306
    restart: always

  egg:
    depends_on:
      - mysql
    build: .
    container_name: egg
    ports:
      - 7001:7001
    restart: always

volumes:
  db-data:
